### PR TITLE
gcp bookshelf md file added and bookshelf list updated

### PR DESCRIPTION
**Pull request by Hafeezbaig**
# Pull Request Checklist

## First Thing

- [x] **Review To Be Published Articles**: Use Deploy Preview (Example Deploy Preview of an older pull request is here - https://github.com/in28minutes/in28minutes.com/pull/11#issuecomment-1902625913)

## Common Mistakes
- [x] **Date of Article**: Date of all blog articles should be yesterday or earlier
- [x] **Notes about pictures in stories**: Make sure that all the required notes are included
- [x] **No Typos**: Make sure that there are no typos in titles or content

## 🎨 Content Verification
- [x] **Image Originality**: Confirm images are original
- [x] **Text Originality**: Ensure all text is original

## ✨ Overall Quality
- [x] **Visual Appeal**: Evaluate layout, colors, typography.
- [x] **Style Consistency**: Check for consistent presentation style.

### CODE REVIEW

**Comment by beena-yatin-kanyal** [comment]
@Hafeezbaig  - 
1. Still the same issue. 404 was reported while clicking the gcp icon from the bookshelf page. Please check.
2. the pr description contains certain checkboxes - ensure to address them before submitting a pr.

**Comment by Hafeezbaig** [comment]
@beena-yatin-kanyal sir, I have troubleshoot the issue and it's now fixed. Please review the latest commit on this branch. Thank you, sir.

**Comment by beena-yatin-kanyal** [comment]
> @beena-yatin-kanyal sir, I have troubleshoot the issue and it's now fixed. Please review the latest commit on this branch. Thank you, sir.

ok. the pr looks ok. please complete the checkbox in pr description and we should be good to merge it.

**Comment by Hafeezbaig** [comment]
@beena-yatin-kanyal sir, I have completed the checkbox in the pr description. We are good to proceed. Thank you sir.

**Comment by beena-yatin-kanyal** [comment]
@Hafeezbaig  - approved.

@in28minutes  - hi Ranga - the pr can be merged. thanks.

**Comment by in28minutes** [comment]
Awesome. Merged now. @Hafeezbaig  Please check if everything is fine!

**Comment by Hafeezbaig** [comment]
@beena-yatin-kanyal @in28minutes I have just checked all the links and everything is working perfectly. Thank you.

**Pull request merged**
